#!/bin/bash

log(){ >&2 echo "$@" ; }
die(){ log "$@" ; exit 1 ; }

##

if [ -z "$1" ] ; then
    RX="hello world"
else
    RX="$1"
fi

case "$2" in
    [0-9])
        OPT="$2"
        ;;
    "")
        OPT=0
        ;;
    *)
        die opt value must be a number
        ;;
esac

[ -z "$CC" ] && CC="gcc"

mkdir -p ./bld || die could not create bld/ directory

./tools/rxengine.py -g "$RX" > ./bld/source.c || die could not create source

${CC}                \
    -S             \
    -O"$OPT"       \
    -Wall          \
    -Wextra        \
    -Werror        \
    -Wfatal-errors \
    -std=gnu99     \
    -o ./bld/rx.s  \
    ./bld/source.c \
    || die failed to compile

${CC}                \
    -O"$OPT"       \
    -Wall          \
    -Wextra        \
    -Werror        \
    -Wfatal-errors \
    -std=gnu99     \
    -o ./bld/rx    \
    ./bld/source.c \
    || die failed to compile

log ... compilation complete ./bld/rx
